android.nonTransitiveRClass=true
android.useAndroidX=true
org.gradle.daemon.idletimeout=10800000
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
kotlin.code.style=official
